
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

homeassistant:
  customize_glob: !include customize_glob.yaml
  customize: !include customize.yaml
  packages:
    house_mode: !include package_house_mode.yaml

zwave:
  device_config: !include zwave_device_config.yaml

################### Homekit #######################
homekit:
  auto_start: false
  filter:
    include_domains:
      - light

################## Google #########################
cloud: !include google_actions.yaml

#################### Zones ###################
zone:
  - name: jobb_guro
    latitude: !secret zone_guro_jobb_lat
    longitude: !secret zone_guro_jobb_lon
    icon: mdi:mother-nurse
    friendly_name: Jobb
  - name: jobb_petter
    latitude: !secret zone_petter_jobb_lat
    longitude: !secret zone_petter_jobb_lon
    friendly_name: Jobb

########### Remote #################
remote:
  - platform: harmony
    name: Harmony Stue
    host: !secret harmony_host

############## Emulated Hue ##############
emulated_hue:
  expose_by_default: false
  entities:
    light.dimmer_stue:
      hidden: false
    light.dimmer_kjokken:
      hidden: false
    group.all_lights:
      hidden: false

light:
  - platform: group
    name: Stue + Kjøkken
    entities:
      - light.dimmer_kjokken
      - light.dimmer_stue

vacuum:
  - platform: xiaomi_miio
    host: !secret xiaomi_host
    token: !secret xiaomi_token

sensor:
  - platform: template
    sensors:
      vacuum_battery_charge:
        value_template: "{{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'battery_level') }}"
      
      vacuum_time_run:
        value_template: "{{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'cleaning_time') }}"
      
      vacuum_time_last_run:
        value_template: "{{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'clean_stop') }}"

      vacuum_area_cleaned:
        value_template: "{{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'cleaned_area') }}"

input_boolean:
  vacuum_autorun:
    name: Vacuum Autorun
    initial: off